plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    id 'com.google.gms.google-services' // KITA TAMBAHKAN PLUGIN FIREBASE
}

android {
    namespace "com.curva.ppob" // 1. UBAH NAMESPACE KE NAMA ASLI APLIKASI
    compileSdk 36

    defaultConfig {
        applicationId "com.curva.ppob" // 2. UBAH APPLICATION ID KE NAMA ASLI APLIKASI
        minSdk 24 // KITA NAIKKAN KE 24 AGAR SESUAI STANDAR SDK 36 DAN PLAY STORE
        targetSdk 36
        versionCode 5
        versionName "5.6.1" // SESUAIKAN DENGAN VERSI TERAKHIR ANDA
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = "11"
    }
    buildFeatures {
        compose true
    }
}

dependencies {
    // BAWAAN JSTUDIO (KITA BIARKAN SAJA AGAR SISTEM TIDAK BENTROK)
    implementation libs.androidx.activity.compose
    implementation platform(libs.androidx.compose.bom)
    implementation libs.androidx.core.ktx
    implementation libs.androidx.lifecycle.runtime.ktx
    implementation libs.androidx.material3
    implementation libs.androidx.ui
    implementation libs.androidx.ui.graphics
    implementation libs.androidx.ui.tooling.preview
    testImplementation libs.junit
    androidTestImplementation platform(libs.androidx.compose.bom)
    androidTestImplementation libs.androidx.espresso.core
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.ui.test.junit4
    debugImplementation libs.androidx.ui.test.manifest
    debugImplementation libs.androidx.ui.tooling

    // ==========================================
    // PUSTAKA BAWAAN CURVA PAYMENT LAMA ANDA
    // ==========================================
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    
    // FIREBASE KITA NAIKKAN VERSINYA AGAR KOMPATIBEL DENGAN SDK 36
    implementation platform('com.google.firebase:firebase-bom:33.1.2')
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-messaging'
    // Firebase IID sudah lama dihapus oleh Google, fiturnya sudah gabung di messaging, jadi tidak perlu dimasukkan lagi.

    // ZXING SCANNER KITA NAIKKAN VERSINYA AGAR KOMPATIBEL DENGAN SDK 36
    implementation 'com.journeyapps:zxing-android-embedded:4.3.0'
}
